### PR TITLE
Fix potential crash after loading of saved game

### LINKED ISSUE #64: Crash in `SV_AreaTriggerEdicts()` function
The given crash is very rare, but it happened from time to time on different maps/mods. Recently, I managed to reproduce a bit more reliably.

The crash occurs consistently at the beginning of Ranger Dynamics level, `rm_dynamics`, from [Re:Mobilize](https://www.slipseer.com/index.php?resources/re-mobilize.239/). Here is a stripped down version of the mod [rm1.0-stripped.zip](https://github.com/sezero/quakespasm/files/11830233/rm1.0-stripped.zip) with saved game included.

Steps to reproduce
* Start the current HEAD (https://github.com/sezero/quakespasm/commit/70df2b661e9c632d04825b259e63ad58c29c01ac) using full or stripped version of the mod, optionally with `-nosound` command line option
* Load Ranger Dynamics, `map rm_dynamics`, and save the game right after that
* Load the saved game
* If it doesn't crash within ten seconds, repeat loading of the saved game, optionally with restarting Quakespasm

Callstack
```
SV_AreaTriggerEdicts(ent=0x000000015e656510, node=0x0000000100599648, list=0x00000001263db4e0, listcount=0x00007ff7bfefeb68, listspace=525) at world.c:294:13
SV_AreaTriggerEdicts(ent=0x000000015e656510, node=0x00000001005995d8, list=0x00000001263db4e0, listcount=0x00007ff7bfefeb68, listspace=525) at world.c:322:3
SV_AreaTriggerEdicts(ent=0x000000015e656510, node=0x00000001005995a0, list=0x00000001263db4e0, listcount=0x00007ff7bfefeb68, listspace=525) at world.c:320:3
SV_AreaTriggerEdicts(ent=0x000000015e656510, node=0x0000000100599568, list=0x00000001263db4e0, listcount=0x00007ff7bfefeb68, listspace=525) at world.c:320:3
SV_AreaTriggerEdicts(ent=0x000000015e656510, node=0x0000000100599530, list=0x00000001263db4e0, listcount=0x00007ff7bfefeb68, listspace=525) at world.c:320:3
SV_TouchLinks(ent=0x000000015e656510) at world.c:347:2
SV_LinkEdict(ent=0x000000015e656510, touch_triggers=true) at world.c:502:3
SV_StepDirection(ent=0x000000015e656510, yaw=2.3561945, dist=1) at sv_move.c:256:3
SV_MoveToGoal at sv_move.c:414:3
PR_ExecuteProgram(fnum=1404) at pr_exec.c:616:4
SV_RunThink(ent=0x000000015e656510) at sv_phys.c:144:2
SV_Physics_Step(ent=0x000000015e656510) at sv_phys.c:1160:2
SV_Physics at sv_phys.c:1218:4
Host_ServerFrame at host.c:650:3
_Host_Frame(time=0.00200000009) at host.c:723:3
Host_Frame(time=0.00200000009) at host.c:786:3
```
Entity class was `monster_army`, but sometimes it crashes on `spark` as well.
Optimization and platform have no effect on it, reproduced with 64-bit Intel macOS and with 32-bit VS2022 debug builds.
Removal of this [`srand()`](https://github.com/sezero/quakespasm/blob/70df2b661e9c632d04825b259e63ad58c29c01ac/Quake/cl_tent.c#L304) call seems to make its reproduction more deterministic.

### PR DESCRIPTION
**Pull request by alexey-lysiuk**
When number of edicts parsed from saved game is smaller than `sv.num_edicts`, "old" edicts are not freed nor unlinked while their memory can be reused by newly spawned entities.

This commit fixes #64.

### CODE REVIEW

**Comment by sezero** [comment]
@ericwa, @Shpoike, @andrei-drexler?

File: Quake/host_cmd.c [hunk 1]
```diff
@@ -1251,6 +1251,10 @@ static void Host_Loadgame_f (void)
 		entnum++;
 	}
 
+	// Free edicts allocated during map loading but no longer used after restoring saved game state
+	for (int i = entnum; i < sv.num_edicts; i++)
```
Comment (sezero) [inline Quake/host_cmd.c:1255]: No C99-ism please: We already have a top-level `i`, so just removing `int ` will be OK.

**Review by sezero — APPROVED** [review]
